config/routes.rb
Rails.application.routes.draw do
  resources :games, only: [:index, :show, :create] do
    resources :guesses, only: [:create]
  end
  root to: "games#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  LIVES_PER_GAME = 10
  LETTERS = "A".."Z"

  has_many :guesses, dependent: :destroy

  before_validation :sanitize_secret, if: :secret?

  validates :secret,
    presence: true,
    format: { with: /\A[A-Z]+\z/, allow_blank: true }

  scope :with_guesses, -> { includes(:guesses) }

  private

  def sanitize_secret
    self.secret = secret.strip.upcase
  end
end

app/models/guess.rb
class Guess < ApplicationRecord
  belongs_to :game

  validates :letter,
    presence: true,
    inclusion: { in: Game::LETTERS, allow_blank: true },
    uniqueness: { scope: :game_id }

  scope :oldest_first, -> { order(:created_at) }

  def <=>(another)
    created_at <=> another.created_at
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :load_game, only: :show

  def index
  end

  def show
    @board = GameState.new(@game)
  end

  def create
    game = Game.create(secret: "SECRET")
    redirect_to game
  end

  private

  def load_game
    @game = Game.with_guesses.find(params[:id])
  end
end

app/controllers/guesses_controller.rb
class GuessesController < ApplicationController
  before_action :load_game

  def create
    CreateGuess.new(@game, guess_params[:letter])
      .on(:correct)   { |guess| flash[:notice] = "Yes! #{guess.letter} is in the word." }
      .on(:incorrect) { |guess| flash[:notice] = "Sorry, #{guess.letter} is not in the word." }
      .on(:failure)   { |guess| flash[:notice] = "You can’t guess #{guess.letter}" }
      .call

    redirect_to @game
  end

  private

  def load_game
    @game = Game.find(params[:game_id])
  end

  def guess_params
    params.require(:guess).permit(:letter)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/_in_progress.html.erb
<p>You have <%= pluralize @board.lives_remaining, "life" %> remaining.</p>

app/views/games/_lost.html.erb
<p>Game over. The word was <%= @board.revealed_word %></p>

app/views/games/_won.html.erb
<p>Congratulations! You guessed the word with <%= pluralize @board.lives_remaining, "life" %> remaining.</p>

app/views/games/index.html.erb
<%= link_to "New game", games_path, method: :post %>

app/views/games/show.html.erb
<h1><%= @board.word %></h1>

<%= form_for :guess, url: game_guesses_path(@board.game_id), html: { disabled: @board.game_over? } do |form| %>
  <% @board.letters.each do |letter| %>
    <%= form.submit letter, name: "guess[letter]", disabled: @board.guessed?(letter) %>
  <% end %>
<% end %>

<%= render partial: @board.status.to_s %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HangmanRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'https://fonts.googleapis.com/css?family=Source+Code+Pro', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main>
      <%= render "shared/flash" %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_flash.html.erb
<%= content_tag :p, flash[:notice], class: "notice" if flash[:notice] %>